[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "{Author}"
name = "{ModName}"
description = "{Description}"
#if (WebsiteUrl != "")
websiteUrl = "{WebsiteUrl}"
#endif
#if (Nsfw)
containsNsfwContent = true
#else
containsNsfwContent = false
#endif
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
#if (DependOnHookGen)
Hamunii-AutoHookGenPatcher = "1.0.2"
#endif

[build]
icon = "icon.png"
#if (SolutionREADME)
readme = "../../README.md"
#else
readme = "../README.md"
#endif
outdir = "../dist"

#if (License)
[[build.copy]]
source = "../../LICENSE"
target = "/"

#endif
#if (Changelog)
[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

#endif
[[build.copy]]
source = "../bin/Release/{Framework}/{AssemblyName}.dll"
target = "/BepInEx/plugins/{ModName}/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "mods" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
